// <auto-generated />
using System;
using LicensePlateDataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LicensePlateDataAccess.Migrations
{
    [DbContext(typeof(LicensePlateDataDbContext))]
    [Migration("20230716230628_seed-licenseplate-simulated-data")]
    partial class seedlicenseplatesimulateddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LicensePlateModels.LicensePlate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<string>("LicensePlateText")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LicensePlates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FileName = "https://plateimagesyyyymmddxyz.blob.core.windows.net/images/FAKE1.jpg",
                            IsProcessed = true,
                            LicensePlateText = "FUNTIME",
                            TimeStamp = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            FileName = "https://plateimagesyyyymmddxyz.blob.core.windows.net/images/FAKE2.jpg",
                            IsProcessed = true,
                            LicensePlateText = "GVMESPD",
                            TimeStamp = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            FileName = "https://plateimagesyyyymmddxyz.blob.core.windows.net/images/FAKE3.jpg",
                            IsProcessed = true,
                            LicensePlateText = "PULTOYS",
                            TimeStamp = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            FileName = "https://plateimagesyyyymmddxyz.blob.core.windows.net/images/FAKE4.jpg",
                            IsProcessed = true,
                            LicensePlateText = "NCC1701",
                            TimeStamp = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            FileName = "https://plateimagesyyyymmddxyz.blob.core.windows.net/images/FAKE5.jpg",
                            IsProcessed = true,
                            LicensePlateText = "MYCAR01",
                            TimeStamp = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            FileName = "https://plateimagesyyyymmddxyz.blob.core.windows.net/images/FAKE6.jpg",
                            IsProcessed = true,
                            LicensePlateText = "FBIAGNT",
                            TimeStamp = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            FileName = "https://plateimagesyyyymmddxyz.blob.core.windows.net/images/FAKE7.jpg",
                            IsProcessed = true,
                            LicensePlateText = "FLYERS1",
                            TimeStamp = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            FileName = "https://plateimagesyyyymmddxyz.blob.core.windows.net/images/FAKE8.jpg",
                            IsProcessed = true,
                            LicensePlateText = "EMC2FST",
                            TimeStamp = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            FileName = "https://plateimagesyyyymmddxyz.blob.core.windows.net/images/FAKE9.jpg",
                            IsProcessed = true,
                            LicensePlateText = "FSTRNU",
                            TimeStamp = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            FileName = "https://plateimagesyyyymmddxyz.blob.core.windows.net/images/FAKE10.jpg",
                            IsProcessed = true,
                            LicensePlateText = "BACKOFF",
                            TimeStamp = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
